config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to:'static_pages#home'
resources :gossips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
validates :anonymous_author, presence: true

validates :content, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
  def new
    @gossip = Gossip.new
  end
def create 
  @gossip = Gossip.create(gossip_params)
redirect_to @gossip

end 
  
  def show
    @gossip = Gossip.find(params[:id])

  end 
  
  
  def edit 
    @gossip = Gossip.find(params[:id])
  end
  
  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to @gossip
  end 

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to @gossips_path
  end 

  def index
    @gossips = Gossip.all
  end 

  
  private

  def gossip_params
    params.require(:gossip).permit(:anonymous_author, :content)

  end 


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gossips/edit.html.erb
<h1>Editer un gossip</h1>

<%= form_for @gossip do |f| %>
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<div class="form-group">
<label>Titre du gossip</label> 
<%= f.text_field :anonymous_author, class: 'form-control'%>
</div>

<div class="form-group">
<label>Contenu du gossip</label> 
<%= f.text_area :content, class: 'form-control'%>

</div>
<div class="form-group">
<button type="submit" class="btn btn-dark">Modifier le gossip</button>
</div>
</div>
<div >
<a href="<%= gossip_path(@gossip.id) %>"  data-method="DELETE" data-confirm="Sur ?">Supprimer le gossip</a>

</div>


<%end%>

app/views/gossips/index.html.erb
<h1>Articles</h1>

<% @gossips.each do |gossip|%>
<h2><%= gossip.anonymous_author%></h2>
<p><%= gossip.content%></p>

<p>
<a href="<%= gossip_path(gossip.id) %>" class="btn btn-dark">Lire la suite</a> 
<a href="<%= edit_gossip_path(gossip.id) %>" class="btn btn-dark">Modifier le gossip</a> 

</p>


<%end%>

app/views/gossips/new.html.erb
<h1>Ajouter un gossip</h1>

<%= form_for @gossip do |f| %>
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<div class="form-group">
<label>Titre du gossip</label> 
<%= f.text_field :anonymous_author, class: 'form-control'%>
</div>

<div class="form-group">
<label>Contenu du gossip</label> 
<%= f.text_area :content, class: 'form-control'%>

</div>
<div class="form-group">
<button type="submit" class="btn btn-dark">Créer un gossip</button>
</div>
<%end%>

app/views/gossips/show.html.erb
<h1><%= @gossip.anonymous_author %></h1>

<p><%= @gossip.content %></p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<%= csrf_meta_tag %>

  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <li><%= link_to "Index des gossips", gossips_path %></li>
        <li><%= link_to "Nouveau gossip", new_gossip_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= render 'layouts/header' %>
 
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= csrf_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_gossip_path, class: "btn btn-lg btn-primary" %>
</div>